### ISSUE TITLE
Cannot run Testsuite with Phantom-JS

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#29]
Stack trace:

```bash
meyerd@ca-meyerd:~/Documents/Workspace/bpmn-io/bpmn-js-properties-panel$ grunt auto-test
Running "karma:unit" (karma) task
INFO [framework.browserify]: registering rebuild (autoWatch=true)
INFO [framework.browserify]: 4011837 bytes written (5.68 seconds)
INFO [framework.browserify]: bundle built
INFO [karma]: Karma v0.12.36 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket 8ixJ6MzMyRP2fNmNOb8P with id 71225075
PhantomJS 1.9.8 (Linux 0.0.0)  should attach a error to an element with error def FAILED
	TypeError: '[object MouseEventConstructor]' is not a constructor (evaluating 'new MouseEvent(( eventType || 'change' ), {
	    view: window,
	    bubbles: true
	  })')
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:50429:0 <- test/TestHelper.js:21:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:50435:0 <- test/TestHelper.js:27:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:51215:0 <- test/spec/provider/parts/specs/EventPropertiesSpec.js:212:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:29943:0 <- node_modules/diagram-js/node_modules/didi/lib/injector.js:81:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:2722:0 <- node_modules/bpmn-js/lib/Viewer.js:249:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:17178:0 <- node_modules/bpmn-js/test/helper/index.js:202:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:2652:0 <- node_modules/bpmn-js/lib/Viewer.js:179:0
	    at importBpmnDiagram (/tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:8954:0 <- node_modules/bpmn-js/lib/import/Importer.js:55:0)
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:2740:0 <- node_modules/bpmn-js/lib/Viewer.js:267:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:2653:0 <- node_modules/bpmn-js/lib/Viewer.js:180:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:9950:0 <- node_modules/bpmn-js/node_modules/bpmn-moddle/node_modules/moddle-xml/lib/reader.js:629:0
	    at /tmp/75f72f4d8cdefeda08da2f67b117fd16.browserify:46093:0 <- node_modules/lodash/internal/baseDelay.js:18:0
PhantomJS 1.9.8 (Linux 0.0.0): Executed 1 of 56 (1 FAILED) ERROR (2.291 secs / 0.084 secs)
^C
```

**Comment by shentschel** [comment]
I put this back for later because of some heavy drawbacks in firefox and phantomJS.

1.) PhantomJS seems to not trigger or register any of our thrown click events 

2.) Firefox can't handle change events on <select> pretty well (will be a seperate bug)
